//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPreference
    {
        public long CustomerPreferenceSerial { get; set; }
        public long CustomerSerial { get; set; }
        public string CustomerLike { get; set; }
        public string CustomerDisLike { get; set; }
        public string CustomerFeedBack { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
    }
}
